=== SmoothyCoronel/DAW.2022-2023/lenguaje de marca/T1/Ejercicios/pedido.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="pedidos" type="pedidoDatos"/>
<xsd:complexType name="pedidoDatos">
<xsd:sequence>
<xsd:element name="sucursal" type="sucursalDatos" minOccurs="1" maxOccurs="unbounded"/>
</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="sucursalDatos">
<xsd:sequence>
<xsd:element name="direccion" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
<xsd:element name="trabajador" type="xsd:string"/>
<xsd:element name="fecha" type="xsd:date"/>
<xsd:element name="observacion" type="xsd:string" minOccurs="0"/>
<xsd:element name="articulo" type="articuloDatos" minOccurs="1" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="codigo" type="codigoTipo" use="required"/>
</xsd:complexType>
<xsd:simpleType name="codigoTipo">
<xsd:restriction base="xsd:string">
<xsd:pattern value="[A-Za-z]([A-Za-z0-9]){7}"/>
</xsd:restriction>
</xsd:simpleType>
<xsd:complexType name="articuloDatos">
<xsd:sequence>
<xsd:element name="unidades">
<xsd:simpleType>
<xsd:restriction base="xsd:positiveInteger">
<xsd:minInclusive value="1"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="precio">
<xsd:simpleType>
<xsd:restriction base="xsd:decimal">
<xsd:minInclusive value="1"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="observaciones" type="xsd:string"/>
<xsd:element name="plazo">
<xsd:simpleType>
<xsd:restriction base="xsd:positiveInteger">
<xsd:minInclusive value="1"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
<xsd:attribute name="codigo" type="codigoArticulo" use="required"/>
</xsd:complexType>
<xsd:simpleType name="codigoArticulo">
<xsd:restriction base="xsd:string">
<xsd:pattern value="[A-Z]{3}-[0-9]{3}"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:schema>

=== SmoothyCoronel/DAW.2022-2023/lenguaje de marca/T1/Ejercicios/pedido-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedidos xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "pedido.xsd" >
      <sucursal codigo="A0b00R01">
            <direccion>C/Castilla, 1</direccion>
            <direccion>C/Castilla, 1</direccion>
            <trabajador>Steve Jobs</trabajador>
            <fecha>2012-01-12</fecha>
            <observacion>Urgente</observacion>
            <articulo codigo="AAA-111">
                  <unidades>12</unidades>
                  <precio>100</precio>
                  <observaciones>Producto muy frágil</observaciones>
                  <plazo>10</plazo>
            </articulo>

            <articulo codigo="AAA-112">
                  <unidades>10</unidades>
                  <precio>10</precio>
                  <observaciones>No apilar más de cinco paquetes</observaciones>
                  <plazo>8</plazo>
            </articulo>
      </sucursal>

      <sucursal codigo="B0000002">
            <direccion>Avda. Gran Vía s/n</direccion>
            <trabajador>Bill Gates</trabajador>
            <fecha>2012-02-10</fecha>
            <articulo codigo="ABC-001">
                  <unidades>5</unidades>
                  <precio>50</precio>
                  <observaciones />
                  <plazo>3</plazo>
            </articulo>
      </sucursal>
</pedidos>
